Repository wescale/hashistack, pull requests merged in 2023-04, with the labels that each got.

#70 Docker & Offline installer documentation
  docs/source/howto/docker_installer.md
  docs/source/reference/role_nomad.md
  docs/source/reference/role_stage1_pip.md
  docs/source/reference/role_vault.md
  docs/source/tutorials.md
  docs/source/tutorials/offline_installer.md
Labels: documentation

#30 feat(devcontainer): Adding default configuration + Fix Make install
  .devcontainer/devcontainer.json
Labels: enhancement

#90 Fix miss configuration
  playbooks/13_core_scaleway_dns_delegation.yml
  playbooks/99_get_creds.yml
  roles/consul/tasks/_tf_configure.yml
  roles/grafana/files/terraform/files/dashboards/nomad.json
  roles/grafana/tasks/debian_11/_configure.yml
  roles/loki/templates/promtail_config.yml.j2
  roles/nomad/templates/nomad.hcl.j2
  roles/prometheus/handlers/main.yml
  roles/prometheus/templates/prometheus.yml.j2
  roles/stage1_bootstrap/tasks/debian_11/_normalize.yml
  roles/vault/files/terraform/consul_integration.tf
  roles/vault/files/terraform/nomad_integration.tf
  roles/vault/tasks/_inplace_init_unseal.yml
  roles/vault/tasks/_inplace_unseal.yml
  roles/vault/tasks/_tf_configure.yml
Labels: bug, enhancement
